### ISSUE TITLE
Submit a Poll Response

### ISSUE THREAD

**Issue by guisselacp** [guisselacp/love-running#1]
In order to **provide anonymous feedback** as a **user**, I can **choose to hide my identity in the poll response**

**Acceptance Criteria:**

- Acceptance Criteria 1: The option should be provided as a checkbox
- Acceptance Criteria 2: The option should appear next to the submit button

**Tasks:**

- [x] Update the view: the poll design (HTML and CSS) to include the checkbox and to show the name of the submitter
- [ ] Update the controller function
- [ ] Test the functionality
